using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using Notlar;

// The main window end to end: editing, folders, selection, attachments, menus, tray and languages.
static partial class Program
{
    static void WindowChecks(string root, VaultSession session, string path, Notebook book)
    {
    var window = new MainWindow(session); window.Show(); Pump();
    window.Activate();
    var title = Find<TextBox>(window, "TitleInput"); var body = Find<TextBox>(window, "BodyInput");
    title.Text = "Yarın için birkaç fikir"; body.Text = "Her şeyi aynı anda yapmak zorunda değilim.\n\nÖnce önemli olanı seç.\nBiraz yavaşla.\nBaşlamak için küçük bir adım yeter.";
    Check(window.SaveNow(), "Editor saves title and text");
    using (var reopened = VaultSession.Open(path, "replacement test passphrase")) Check(reopened.Book.Notes[0].Title == title.Text && reopened.Book.Notes[0].Text == body.Text, "Actual editor content survives reopen");
    Click(window, "NewButton");
    Check(title.IsKeyboardFocused, "New note focuses title for immediate typing");
    title.Text = "Hafta sonu"; body.Text = "Uzun bir yürüyüş.\nYarım kalan kitaba dön.\nKahveyi acele etmeden iç.";
    var autoSaveWatch = Stopwatch.StartNew();
    while (Find<TextBlock>(window, "StatusText").Text == L10n.T("Saving") && autoSaveWatch.ElapsedMilliseconds < 3000) { Pump(); Thread.Sleep(10); }
    Check(Find<TextBlock>(window, "StatusText").Text == L10n.T("SavedEncrypted"), "Debounced automatic save completes without save command");
    Check(session.Book.Notes.Count == 2, "New note via real UI handler");
    var search = Find<TextBox>(window, "SearchInput"); search.Text = "yürüyüş"; Pump();
    Check(Find<ListBox>(window, "NoteList").Items.Count == 1, "UI searches note bodies");
    search.Text = "unmatched-query"; Pump();
    Check(Find<ListBox>(window, "NoteList").Items.Count == 0 && Find<Grid>(window, "EditorArea").Visibility == Visibility.Collapsed, "Empty search hides unrelated editor content");
    search.Clear(); Pump();
    Click(window, "DeleteButton");
    Check(session.Book.Notes.Count(n => n.Deleted) == 1, "Soft delete retains note");
    Click(window, "UndoDelete"); Check(session.Book.Notes.All(n => !n.Deleted), "Delete undo restores note");
    Click(window, "DeleteButton"); Click(window, "TrashFilter");
    Check(body.IsReadOnly, "Trash content cannot be accidentally edited");
    Click(window, "RestoreButton"); Check(session.Book.Notes.All(n => !n.Deleted), "Trash restore returns note");
    var pinTarget = (Note)Find<ListBox>(window, "NoteList").SelectedItem; bool wasPinned = pinTarget.Pinned;
    Click(window, "PinButton"); Check(pinTarget.Pinned != wasPinned, "Pin toggles from UI");
    var archiveTarget = (Note)Find<ListBox>(window, "NoteList").SelectedItem; int liveBefore = Find<ListBox>(window, "NoteList").Items.Count;
    Click(window, "ArchiveButton"); Pump();
    Check(archiveTarget.Archived && Find<ListBox>(window, "NoteList").Items.Count == liveBefore - 1 && Find<Button>(window, "ArchiveFilter").Visibility == Visibility.Visible, "Archive button moves the note out of the main list");
    Click(window, "ArchiveFilter"); Pump();
    Check(Find<ListBox>(window, "NoteList").Items.Cast<Note>().Single() == archiveTarget && !body.IsReadOnly && Find<Button>(window, "EmptyNew").Visibility == Visibility.Collapsed && (string)Find<Button>(window, "ArchiveButton").ToolTip == L10n.T("UnarchiveNote"), "The archive lists the note, still editable, with an unarchive button");
    Click(window, "ArchiveButton"); Pump();
    Check(!archiveTarget.Archived && Find<ListBox>(window, "NoteList").Items.Count == 0, "Unarchiving from the archive empties it");
    Click(window, "AllFilter"); Pump();
    Check(Find<ListBox>(window, "NoteList").Items.Count == liveBefore, "The note is back in the main list");
    Click(window, "NewButton"); title.Text = "Toplu 1"; body.Text = "PURGE-ME-4411"; window.SaveNow();
    Click(window, "NewButton"); title.Text = "Toplu 2"; window.SaveNow();
    var noteList = Find<ListBox>(window, "NoteList");
    Click(window, "SelectButton");
    Check(noteList.SelectionMode == SelectionMode.Multiple && Find<Grid>(window, "EditorArea").Visibility == Visibility.Collapsed && Find<StackPanel>(window, "SelectionState").Visibility == Visibility.Visible, "Select mode shows checkboxes and hides the editor");
    Check(Visuals<CheckBox>(noteList).Count(c => c.IsVisible) == 4 && !Find<Button>(window, "BulkDeleteButton").IsEnabled, "Every card gets a checkbox; bulk delete waits for a selection");
    Click(window, "SelectAllButton");
    Check(noteList.SelectedItems.Count == 4 && Find<TextBlock>(window, "SelectionCount").Text == L10n.Count("SelectedCountOne", "SelectedCountMany", 4), "Select all checks every listed note");
    Click(window, "SelectAllButton"); Check(noteList.SelectedItems.Count == 0, "Select all toggles back to none");
    noteList.SelectedItems.Add(noteList.Items[0]); noteList.SelectedItems.Add(noteList.Items[1]); Pump();
    Check(Find<Button>(window, "BulkDeleteButton").IsEnabled && Find<TextBlock>(window, "SelectionHeading").Text == L10n.Count("SelectedCountOne", "SelectedCountMany", 2), "Checking cards enables bulk actions");
    Click(window, "BulkDeleteButton");
    Check(session.Book.Notes.Count(n => n.Deleted) == 2 && session.Book.Notes.Where(n => n.Deleted).All(n => n.DeletedAt != null) && noteList.SelectionMode == SelectionMode.Single, "Bulk delete moves the checked notes to trash with timestamps and leaves select mode");
    Click(window, "UndoDelete"); Check(session.Book.Notes.All(n => !n.Deleted), "Undo restores every bulk-deleted note");
    Click(window, "SelectButton"); Click(window, "SelectAllButton"); Find<Button>(window, "SelectAllButton").Focus(); Pump();
    window.RaiseEvent(new KeyEventArgs(Keyboard.PrimaryDevice, PresentationSource.FromVisual(window), 0, Key.Delete) { RoutedEvent = UIElement.PreviewKeyDownEvent }); Pump();
    Check(session.Book.Notes.Count(n => n.Deleted) == 4 && noteList.SelectionMode == SelectionMode.Single, "Delete key removes the checked notes even when a toolbar button has focus");
    Click(window, "UndoDelete"); Check(session.Book.Notes.All(n => !n.Deleted), "Undo after keyboard bulk delete restores everything");
    Check(Find<Button>(window, "BulkDeleteButton").Content as string == L10n.T("Delete") && Find<Button>(window, "DeleteButton").ToolTip as string == L10n.T("Delete"), "The primary bulk action is plainly labeled Delete");
    Click(window, "NewButton"); title.Text = "Geçici"; window.SaveNow();
    Click(window, "SelectButton"); noteList.SelectedItems.Add(session.Book.Notes.First(n => n.Title == "Geçici")); Pump();
    Check(Find<Button>(window, "SelectionDeleteButton").IsVisible && Find<Button>(window, "BulkPurgeButton").IsVisible && Find<Button>(window, "BulkPurgeButton").IsEnabled, "Select mode offers Delete in the sidebar and permanent delete from All notes too");
    window.ConfirmDestructive = _ => true; Click(window, "BulkPurgeButton");
    Check(session.Book.Notes.Count == 4 && session.Book.Notes.All(n => n.Title != "Geçici") && noteList.SelectionMode == SelectionMode.Single, "Permanent delete from All notes removes the checked note outright");
    body.Focus(); Pump();
    window.RaiseEvent(new KeyEventArgs(Keyboard.PrimaryDevice, PresentationSource.FromVisual(window), 0, Key.Delete) { RoutedEvent = UIElement.PreviewKeyDownEvent }); Pump();
    Check(session.Book.Notes.All(n => !n.Deleted), "Delete key inside the editor edits text instead of deleting the note");
    Click(window, "SelectButton"); Click(window, "SelectAllButton"); Click(window, "BulkDeleteButton");
    Check(session.Book.Notes.Count(n => n.Deleted) == 4, "Select all then delete empties the list");
    Click(window, "TrashFilter");
    Check(Find<TextBlock>(window, "TrashNotice").Visibility == Visibility.Visible && Find<Button>(window, "PurgeButton").Visibility == Visibility.Visible && Find<Button>(window, "ExportButton").Visibility == Visibility.Collapsed, "Trash explains the 30-day limit and offers permanent delete");
    var purgeTarget = session.Book.Notes.First(n => n.Text == "PURGE-ME-4411"); noteList.SelectedItem = purgeTarget; Pump();
    Check(purgeTarget.TrashLabel == L10n.T("TrashLabelDays", 30), "Trash card shows remaining days");
    bool asked = false; window.ConfirmDestructive = _ => { asked = true; return false; };
    Click(window, "PurgeButton"); Check(asked && session.Book.Notes.Contains(purgeTarget), "Permanent delete asks first and a declined dialog keeps the note");
    window.ConfirmDestructive = _ => true;
    Click(window, "PurgeButton");
    Check(!session.Book.Notes.Contains(purgeTarget) && session.Book.Notes.Count == 3, "Confirmed permanent delete removes the note from the notebook");
    using (var reopened = VaultSession.Open(path, "replacement test passphrase")) Check(reopened.Book.Notes.All(n => n.Id != purgeTarget.Id), "Purged note is gone after reopen");
    using (var reopenedBackup = VaultSession.Open(path + ".bak", "replacement test passphrase")) Check(reopenedBackup.Book.Notes.All(n => n.Id != purgeTarget.Id), "Purged note is also gone from the rolling backup");
    Click(window, "SelectButton"); noteList.SelectedItems.Add(noteList.Items[0]); noteList.SelectedItems.Add(noteList.Items[1]); Pump();
    Click(window, "BulkPurgeButton");
    Check(session.Book.Notes.Count == 1 && session.Book.Notes[0].Deleted, "Bulk permanent delete removes the checked trash notes");
    Click(window, "SelectButton"); Click(window, "SelectAllButton"); Click(window, "BulkRestoreButton");
    Check(session.Book.Notes.All(n => !n.Deleted && n.DeletedAt == null) && Find<TextBlock>(window, "ListHeading").Text == L10n.T("MyNotes") && Find<Grid>(window, "EditorArea").Visibility == Visibility.Visible, "Bulk restore returns notes and reopens the editor");
    // Portable backup: password-protected, independent of this Windows account.
    string portable = Path.Combine(root, "portable.vault");
    window.AskPassword = _ => "portable backup passphrase 42";
    Check(window.ExportBackup(portable, "portable backup passphrase 42") && File.Exists(portable) && !File.ReadAllText(portable).Contains("Yarın"), "Portable backup is written encrypted");
    Reject(() => VaultSession.OpenBackup(portable, "wrong passphrase 12345"), "Portable backup rejects a wrong password");
    Reject(() => VaultSession.OpenBackup(portable, null), "Portable backup requires a password");
    using (var opened = VaultSession.OpenBackup(portable, "portable backup passphrase 42")) Check(opened.Book.Notes.Count == session.Book.Notes.Count && opened.Book.Id == session.Book.Id, "Portable backup opens with its password alone (no DPAPI)");
    var before = session.Book.Notes.Count;
    var edited = session.Book.Notes[0]; string keepTitle = edited.Title;
    edited.Title = "Sonradan düzenlendi"; edited.Revision++; edited.Updated = DateTimeOffset.UtcNow; window.SaveNow();
    Check(window.RestoreBackup(portable, "portable backup passphrase 42") && session.Book.Notes.Count == before && session.Book.Notes[0].Title == "Sonradan düzenlendi" && Find<TextBlock>(window, "StatusText").Text == L10n.T("RestoreNothing"), "Restoring an older backup never overwrites newer local edits");
    session.Book.Notes.Remove(edited); dirty(window);
    Check(window.RestoreBackup(portable, "portable backup passphrase 42") && session.Book.Notes.Any(n => n.Id == edited.Id && n.Title == keepTitle) && Find<TextBlock>(window, "StatusText").Text == L10n.T("RestoreResult", 1, 0), "Restoring adds notes missing locally and reports the count");
    Check(!window.RestoreBackup(portable, "wrong passphrase 12345") && Find<TextBlock>(window, "StatusText").Text == L10n.T("PasswordWrong"), "Wrong restore password is reported, nothing changes");
    var merged = new Notebook { Notes = [new Note { Id = "a", Title = "old", Revision = 1 }, new Note { Id = "b", Title = "local newer", Revision = 3 }] };
    var incoming = new Notebook { Notes = [new Note { Id = "a", Title = "new", Revision = 2 }, new Note { Id = "b", Title = "backup older", Revision = 2 }, new Note { Id = "c", Title = "only in backup", Revision = 1 }] };
    var stats = VaultSession.Merge(merged, incoming);
    Check(stats == (1, 1) && merged.Notes.Single(n => n.Id == "a").Title == "new" && merged.Notes.Single(n => n.Id == "b").Title == "local newer" && merged.Notes.Count == 3, "Merge keeps the higher revision per note and adds unknown notes");
    // Drag and drop of TXT files.
    string drop1 = Path.Combine(root, "Bırakılan 1.txt"), drop2 = Path.Combine(root, "Bırakılan 2.txt"), dropBad = Path.Combine(root, "resim.png");
    File.WriteAllText(drop1, "ilk", new UTF8Encoding(false)); File.WriteAllText(drop2, "ikinci", new UTF8Encoding(false)); File.WriteAllBytes(dropBad, [1, 2]);
    int dropped = window.ImportDropped([drop1, drop2]);
    Check(dropped == 2 && session.Book.Notes.Count(n => n.Title.StartsWith("Bırakılan")) == 2 && Find<TextBlock>(window, "StatusText").Text == L10n.T("TxtImportedMany", 2), "Dropping TXT files imports each one as a note");
    Check(window.AllowDrop, "Main window accepts file drops");
    // Other text formats: Markdown (task lists become checklists), HTML (tags stripped), RTF and DOCX (text only).
    string mdFile = Path.Combine(root, "Plan.md"); File.WriteAllText(mdFile, "# Plan\n\n- [ ] Süt\n- [x] Ekmek\n\nNot.\n", new UTF8Encoding(false));
    var mdNote = TextFiles.Read(mdFile);
    Check(mdNote.Title == "Plan" && mdNote.Text == "# Plan\n\n" + Checklist.OpenPrefix + "Süt\n" + Checklist.DonePrefix + "Ekmek\n\nNot.\n", "Markdown opens as a note and its task list becomes a checklist");
    string mdOut = Path.Combine(root, "out.md"); TextFiles.Write(mdOut, new Note { Title = "Liste", Text = Checklist.OpenPrefix + "Süt\n" + Checklist.DonePrefix + "Ekmek\ndüz" });
    Check(File.ReadAllText(mdOut) == "# Liste\n\n- [ ] Süt\n- [x] Ekmek\ndüz\n", "Saving as Markdown writes the title as a heading and checklists as task lists");
    string htmlFile = Path.Combine(root, "sayfa.html"); File.WriteAllText(htmlFile, "<html><head><style>p{}</style><script>x=1</script></head><body><h1>Başlık</h1><p>Bir &amp; iki<br>üç</p></body></html>");
    Check(TextFiles.Read(htmlFile).Text == "Başlık\nBir & iki\nüç", "HTML opens as its readable text");
    string rtfFile = Path.Combine(root, "eski.rtf"); File.WriteAllText(rtfFile, @"{\rtf1\ansi\ansicpg1254{\fonttbl{\f0 Arial;}}\f0 Merhaba \b d\u252?nya\b0\par ikinci sat\u305?r\par}");
    var rtfNote = TextFiles.Read(rtfFile); Check(rtfNote.Text.Replace("\n", "|") == "Merhaba dünya|ikinci satır", "RTF opens as plain text without formatting codes");
    string docxFile = Path.Combine(root, "belge.docx");
    using (var zip = new System.IO.Compression.ZipArchive(File.Create(docxFile), System.IO.Compression.ZipArchiveMode.Create))
    using (var writer = new StreamWriter(zip.CreateEntry("word/document.xml").Open()))
        writer.Write("<?xml version=\"1.0\"?><w:document xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\"><w:body><w:p><w:r><w:t>Birinci</w:t></w:r><w:r><w:tab/><w:t>paragraf</w:t></w:r></w:p><w:p><w:r><w:t>İkinci</w:t></w:r></w:p></w:body></w:document>");
    Check(TextFiles.Read(docxFile).Text == "Birinci\tparagraf\nİkinci", "A Word document opens as its paragraphs");
    Check(TextFiles.IsSupported("a.LOG") && TextFiles.IsSupported("b.markdown") && !TextFiles.IsSupported("c.exe") && TextFiles.SuggestedName(new Note { Title = "x" }, ".md") == "x.md", "Common text types are recognised by extension");
    Reject(() => TextFiles.Read(dropBad), "Unsupported types are refused");
    Check(window.ImportDropped([mdFile, htmlFile]) == 2 && session.Book.Notes.Any(n => n.Title == "sayfa"), "Dropping Markdown and HTML files imports them as notes");
    // Photos and videos on a note.
    var photoNote = (Note)Find<ListBox>(window, "NoteList").SelectedItem;
    string photoFile = Path.Combine(root, "Deniz kenarı.png"); File.WriteAllBytes(photoFile, Png(800, 500, Colors.DarkOrange));
    string videoFile = Path.Combine(root, "yürüyüş.mp4"); var clip = new byte[3 * 1024 * 1024 + 123]; RandomNumberGenerator.Fill(clip); File.WriteAllBytes(videoFile, clip);
    var attaching = window.AttachFilesAsync([photoFile, videoFile, drop1]);
    while (!attaching.IsCompleted) { Pump(); Thread.Sleep(10); }
    Check(attaching.Result == 2 && photoNote.Attachments.Count == 2 && Find<TextBlock>(window, "StatusText").Text == L10n.T("AttachmentSelectFile"), "Attaching a photo and a video reports the unsupported file and keeps the two media files");
    var panel = Find<WrapPanel>(window, "AttachmentPanel");
    Check(Find<ScrollViewer>(window, "AttachmentScroll").Visibility == Visibility.Visible && panel.Children.Count == 2, "Attachment strip shows one tile per file");
    var thumbnail = Visuals<Image>(panel).First();
    var thumbWatch = Stopwatch.StartNew(); while (thumbnail.Source == null && thumbWatch.ElapsedMilliseconds < 5000) { Pump(); Thread.Sleep(20); }
    Check(thumbnail.Source is BitmapSource thumb && thumb.PixelWidth == 264, "Photo tile decodes a small thumbnail from the encrypted file");
    Check(session.Attachments.Exists(photoNote.Attachments[0]) && session.Attachments.Directory == Path.Combine(Path.GetDirectoryName(path)!, "attachments"), "Encrypted attachment files live in the attachments folder beside the vault");
    using (var reopened = VaultSession.Open(path, "replacement test passphrase")) Check(reopened.Book.Notes.Single(n => n.Id == photoNote.Id).Attachments.Count == 2, "Attachment metadata is saved with the note");
    search.Text = "yürüyüş.mp4"; Pump();
    Check(Find<ListBox>(window, "NoteList").Items.Count == 1 && photoNote.AttachmentLabel == L10n.T("AttachmentCountMany", 2), "Search finds notes by attachment name; the card shows the attachment count");
    search.Clear(); Pump();
    var viewer = new AttachmentWindow(window, session.Attachments, photoNote.Attachments[0]); viewer.Show(); Pump();
    Check(Find<Image>(viewer, "Picture").Source is BitmapSource full && full.PixelWidth == 800 && Find<TextBlock>(viewer, "NameText").Text == "Deniz kenarı.png", "Viewer shows the full decrypted photo");
    viewer.Close(); Pump();
    string copy = Path.Combine(root, "kopya.mp4");
    Check(window.SaveAttachmentCopy(photoNote.Attachments[1], copy) && File.ReadAllBytes(copy).SequenceEqual(clip), "Save a copy writes the decrypted original");
    Check(window.AttachImage(Bitmap(200, 120, Colors.Teal)) && photoNote.Attachments.Count == 3 && photoNote.Attachments[2].MediaType == "image/png" && photoNote.Attachments[2].Width == 200, "A pasted picture becomes a PNG attachment");
    string bulkFolder = Path.Combine(root, "bulk-save"); Directory.CreateDirectory(bulkFolder); File.WriteAllText(Path.Combine(bulkFolder, "Deniz kenarı.png"), "taken");
    int bulkSaved = window.SaveAttachments([photoNote], bulkFolder);
    Check(bulkSaved == 3 && File.Exists(Path.Combine(bulkFolder, "Deniz kenarı (2).png")) && File.ReadAllBytes(Path.Combine(bulkFolder, "yürüyüş.mp4")).SequenceEqual(clip), "Saving all attachments writes every file, never overwriting an existing name");
    string attachedBackup = Path.Combine(root, "with-files.vault");
    Check(window.ExportBackup(attachedBackup, "portable backup passphrase 42") && Directory.GetFiles(VaultSession.BackupFilesDirectory(attachedBackup)).Length == 3, "Portable backup carries the encrypted attachment files beside it");
    string restoreRoot = Path.Combine(root, "restore-target"); Directory.CreateDirectory(restoreRoot);
    using (var target = VaultSession.CreateDevice(Path.Combine(restoreRoot, "notes.vault")))
    {
        target.Save();
        var targetWindow = new MainWindow(target); targetWindow.Show(); Pump();
        Check(targetWindow.RestoreBackup(attachedBackup, "portable backup passphrase 42") && target.Attachments.ReadAll(target.Book.Notes.Single(n => n.Id == photoNote.Id).Attachments[1]).SequenceEqual(clip), "Restoring a backup on another vault brings the attachments along and decrypts them there");
        targetWindow.Close();
    }
    // Picking: the check circle (or Ctrl+click) marks tiles; the bar above the grid saves or removes them together.
    window.PickAttachment(photoNote.Attachments[0]); window.PickAttachment(photoNote.Attachments[2]); Pump();
    Check(window.PickedAttachments.Count == 2 && Find<DockPanel>(window, "AttachmentBar").Visibility == Visibility.Visible && Find<TextBlock>(window, "AttachmentCount").Text == L10n.T("AttachmentsSelected", 2), "Picking two attachments shows the selection bar with a count");
    Snapshot(window, "attachments-picked");
    string pickedFolder = Path.Combine(root, "picked-out");
    Check(window.SaveAttachmentCopies(photoNote.Attachments.Where(a => window.PickedAttachments.Contains(a.Id)).ToList(), pickedFolder) && Directory.GetFiles(pickedFolder).Length == 2 && window.PickedAttachments.Count == 0, "Saving the picked attachments writes just those files and clears the selection");
    window.PickAttachment(photoNote.Attachments[0], false); Check(window.PickedAttachments.Count == 0 && Find<DockPanel>(window, "AttachmentBar").Visibility == Visibility.Collapsed, "Unpicking the last attachment hides the bar");
    var removed = photoNote.Attachments[1]; string removedPath = session.Attachments.PathFor(removed);
    window.ConfirmRemoveAttachment = _ => false;
    Check(!window.RemoveAttachment(removed) && photoNote.Attachments.Count == 3 && File.Exists(removedPath), "Declining the removal prompt keeps the attachment");
    window.ConfirmRemoveAttachment = _ => true;
    Check(window.RemoveAttachment(removed) && photoNote.Attachments.Count == 2 && !File.Exists(removedPath) && panel.Children.Count == 2 && Find<TextBlock>(window, "StatusText").Text == L10n.T("AttachmentRemoved"), "Removing an attachment deletes its encrypted file");
    window.PickAttachment(photoNote.Attachments[1]); window.ConfirmRemoveAttachment = _ => true;
    Check(window.RemovePicked() && photoNote.Attachments.Count == 1 && panel.Children.Count == 1 && Find<TextBlock>(window, "StatusText").Text == L10n.T("AttachmentsRemoved", 1), "Removing the picked attachments takes them off the note");
    Click(window, "DeleteButton"); Click(window, "TrashFilter"); Pump();
    Check(Find<Button>(window, "AttachButton").Visibility == Visibility.Collapsed && File.Exists(session.Attachments.PathFor(photoNote.Attachments[0])), "A note in Recently deleted cannot take attachments but keeps its files");
    window.ConfirmDestructive = _ => true; Click(window, "PurgeButton");
    Check(!session.Book.Notes.Contains(photoNote) && !File.Exists(session.Attachments.PathFor(photoNote.Attachments[0])) && Directory.GetFiles(session.Attachments.Directory, "*.bin").Length == 0, "Permanently deleting a note removes its attachment files");
    Click(window, "AllFilter"); Pump();
    var passwordDialog = new PasswordDialog(window, L10n.T("BackupPasswordTitle"), L10n.T("BackupPasswordCreate"), true); passwordDialog.Show(); Pump();
    Find<PasswordBox>(passwordDialog, "Password").Password = "short"; Click(passwordDialog, "Submit");
    Check(passwordDialog.IsVisible && Find<TextBlock>(passwordDialog, "Error").Visibility == Visibility.Visible, "Password dialog refuses short passwords");
    Find<PasswordBox>(passwordDialog, "Password").Password = "portable backup passphrase 42"; Find<PasswordBox>(passwordDialog, "Confirm").Password = "different passphrase 4242"; Click(passwordDialog, "Submit");
    Check(passwordDialog.IsVisible && Find<TextBlock>(passwordDialog, "Error").Text == L10n.T("PasswordMismatch"), "Password dialog refuses mismatched confirmation");
    passwordDialog.Close();
    Sounds.Enabled = false;
    var confirm = new MessageDialog(window, L10n.T("DeletePermanently"), L10n.T("ConfirmPurgeOne", "Deneme"), L10n.T("DeletePermanently"), L10n.T("Cancel"), danger: true); confirm.Show(); Pump();
    Check(Find<Button>(confirm, "Primary").Style == confirm.FindResource("DangerButton") && Find<Button>(confirm, "Secondary").IsKeyboardFocused && Visuals<Button>(confirm).Count() == 2, "Themed confirmation uses a red primary action and focuses Cancel by default");
    confirm.Close();
    Check(Assembly.GetAssembly(typeof(Sounds))!.GetManifestResourceStream("Notlar.Sounds.click.wav") is { Length: > 1000 }, "The click sound is embedded in the application");
    Sounds.Enabled = true; Sounds.Click();
    Check(!Directory.Exists("src") || Directory.GetFiles(Path.Combine("src", "Notlar"), "*.cs").Where(f => !f.EndsWith("GateWindow.xaml.cs")).All(f => !File.ReadAllText(f).Contains("MessageBox.Show")), "No system message boxes remain outside the legacy gate window");
    var backupMenu = Find<ContextMenu>(window, "BackupMenu");
    Check(backupMenu.Items.Count == 2 && TextFiles.SuggestedName(new Note { Title = "Alışveriş: süt/ekmek?" }) == "Alışveriş_ süt_ekmek_.txt", "Backup menu offers create and restore; export suggests the note title as file name");
    title.Text = "Kaydedilemeyen değişiklik";
    string moved = path + ".held"; File.Move(path, moved); Directory.CreateDirectory(path);
    Check(!window.SaveNow(), "Failed write is reported, never falsely marked saved");
    Directory.Delete(path); File.Move(moved, path);
    Check(window.SaveNow(), "Failed save can be retried without losing editor text");
    title.Text = "Yarın için birkaç fikir"; window.SaveNow();
    window.Width = 800; window.Height = 560; Pump();
    Check(body.ActualWidth > 300 && body.ActualHeight > 200, "Editor remains usable at minimum window size");
    window.WindowState = WindowState.Maximized; Pump(); Thread.Sleep(300); Pump();
    var hwnd = new System.Windows.Interop.WindowInteropHelper(window).Handle;
    bool placed = WindowPlacement.GetWindowRect(hwnd, out var rect) & WindowPlacement.TryGetWorkArea(hwnd, out var work, out _);
    Check(placed && rect.Left >= work.Left && rect.Top >= work.Top && rect.Right <= work.Right && rect.Bottom <= work.Bottom
        && rect.Bottom - rect.Top >= work.Bottom - work.Top - 2, "Maximized window fills exactly the work area: nothing hidden under the taskbar or off-screen");
    var countText = Find<TextBlock>(window, "CountText");
    var countBottom = countText.PointToScreen(new Point(0, countText.ActualHeight));
    Check(countText.IsVisible && countBottom.Y <= work.Bottom && Find<Button>(window, "LanguageButton").PointToScreen(new Point(0, 0)).Y < work.Bottom, "Sidebar bottom row stays on screen when maximized");
    window.WindowState = WindowState.Normal; Pump();
    window.Width = 1900; window.Height = 1000; Pump();
    var editorArea = Find<Grid>(window, "EditorArea");
    var editorLeft = editorArea.TranslatePoint(new Point(0, 0), window).X;
    double bodyRight = body.TranslatePoint(new Point(body.ActualWidth, 0), window).X;
    Check(body.ActualWidth > window.ActualWidth - 304 - 48 - 12 - 2 && editorLeft < 400 && window.ActualWidth - bodyRight < 20, "Wide window stretches the editor to the right edge with its scrollbar at the edge");
    var textMenu = body.ContextMenu!; textMenu.PlacementTarget = body; textMenu.IsOpen = true; Pump();
    Check(textMenu.Items.Count == 4 && textMenu.Items.OfType<Separator>().Count() == 0 && textMenu.Items.OfType<MenuItem>().Any(m => (string)m.Header == L10n.T("Paste")) && textMenu.ActualWidth > 100, "Editor text boxes get the themed cut/copy/paste menu");
    textMenu.IsOpen = false; Pump();
    var languageMenu = Find<ContextMenu>(window, "LanguageMenu");
    Check(languageMenu.Items.Count == L10n.Languages.Length && languageMenu.Items.OfType<MenuItem>().Single(m => m.IsChecked).Tag as string == "en", "Language menu lists every language and marks the current one");
    var listMenu = Find<ListBox>(window, "NoteList").ContextMenu!;
    Check(listMenu.Items.OfType<MenuItem>().Count() == 7, "Note cards get a themed action menu");
    window.Width = 1160; window.Height = 780; Pump();
    Find<ListBox>(window, "NoteList").SelectedIndex = 0; Pump();
    // Closing only hides the window: the app stays in the notification area so the phone can keep syncing.
    window.Close(); Pump();
    Check(!window.IsVisible && new System.Windows.Interop.WindowInteropHelper(window).Handle != IntPtr.Zero && session.Book.Notes.Count > 0, "Closing the window hides it to the tray instead of quitting");
    window.ShowFromTray(); Pump();
    Check(window.IsVisible, "The tray brings the window back");
    var appSettings = AppSettings.Load(Path.GetDirectoryName(path)!); appSettings.TrayHintShown = true; appSettings.Language = "tr"; appSettings.Save();
    var reloaded = AppSettings.Load(Path.GetDirectoryName(path)!);
    Check(reloaded.TrayHintShown && reloaded.Language == "tr" && L10n.Detect(Path.GetDirectoryName(path)!) == "tr", "Settings keep the language and the tray hint flag together");
    Check(File.ReadAllText("setup/Notlar.iss").Contains(@"CurrentVersion\Run") && File.ReadAllText("setup/Notlar.iss").Contains("--minimized"), "The installer offers start-with-Windows into the tray");
    Check(Find<Button>(window, "DeleteButton").Focusable == false, "Toolbar icon buttons do not keep a focus ring after a click");
    // Checklists: plain lines with a marker, drawn as check boxes.
    string cl = "Plan\n" + Checklist.OpenPrefix + "Süt\n" + Checklist.DonePrefix + "Ekmek";
    Check(Checklist.IsItem(Checklist.LineAt(cl, 6)) && !Checklist.IsDone(Checklist.LineAt(cl, 6)) && Checklist.Body(Checklist.LineAt(cl, cl.Length - 1)) == "Ekmek", "Checklist markers are recognised per line");
    Check(Checklist.Toggle(Checklist.OpenPrefix + "a") == Checklist.DonePrefix + "a" && Checklist.Toggle("plain") == "plain", "Toggling flips open and done");
    var enter = Checklist.Enter(cl, cl.Length); Check(enter != null && enter.Value.Text.EndsWith("Ekmek\n" + Checklist.OpenPrefix) && enter.Value.Caret == enter.Value.Text.Length, "Enter at the end of an item starts the next item");
    var endList = Checklist.Enter(cl + "\n" + Checklist.OpenPrefix, cl.Length + 3); Check(endList != null && endList.Value.Text == cl + "\n", "Enter on an empty item ends the list");
    var back = Checklist.Backspace(cl, 7); Check(back != null && back.Value.Text == "Plan\nSüt\n" + Checklist.DonePrefix + "Ekmek", "Backspace right after a marker removes it");
    var toggled = Checklist.ToggleLines("a\nb", 0, 3, out _, out _); Check(toggled == Checklist.OpenPrefix + "a\n" + Checklist.OpenPrefix + "b" && Checklist.ToggleLines(toggled, 0, toggled.Length, out _, out _) == "a\nb", "Ctrl+Shift+L turns selected lines into items and back");
    Check(Checklist.Preview(cl) == "Plan\nSüt\n\u2713 Ekmek", "Previews read the markers as words");
    body.Text = cl; Pump(); window.ToggleItem(5); Pump();
    Check(body.Text.Contains(Checklist.DonePrefix + "Süt"), "Clicking the box toggles the item in the editor");
    body.CaretIndex = 5; Pump(); Check(body.CaretIndex == 7, "The caret cannot rest inside a marker");
    body.CaretIndex = 2; Click(window, "ChecklistButton");
    Check(body.Text.StartsWith(Checklist.OpenPrefix + "Plan") && window.SaveNow() && session.Book.Notes.Any(n => n.Text.StartsWith(Checklist.OpenPrefix + "Plan")), "The toolbar button turns the current line into an item and it is saved as plain text");
    var fromTag = Updater.FromTagUrl("https://github.com/Obirize/NoteBook/releases/tag/v9.8.7");
    Check(fromTag != null && fromTag.Version == new Version(9, 8, 7) && fromTag.InstallerUrl.EndsWith("/releases/download/v9.8.7/NoteBook-Setup-9.8.7.exe") && fromTag.ChecksumUrl!.EndsWith(".sha256") && Updater.FromTagUrl("https://github.com/x/y/releases") == null, "The releases page redirect alone is enough to find the newest installer");
    Click(window, "LockButton"); Check(window.LockRequested && !window.IsVisible && body.Text == "", "Lock closes and clears visible plaintext");
    session.Dispose(); Reject(session.Save, "Disposed session cannot save");
    var large = new Notebook { Notes = Enumerable.Range(0, 1000).Select(i => new Note { Title = "Not " + i, Text = new string('x', 1000) }).ToList() };
    var bulk = VaultSession.Create(Path.Combine(root, "bulk.vault"), Password, large); using var bulkSession = bulk.Session;
    bulkSession.Save(); var results = NoteQuery.Find(large, "Not 99", Folder.Notes);
    Check(results.Count == 11, "1000-note search returns correct matches");
    var empty = VaultSession.Create(Path.Combine(root, "empty.vault"), Password); using var emptySession = empty.Session; emptySession.Save();
    var emptyWindow = new MainWindow(emptySession); emptyWindow.Show(); Pump();
    Check(Find<StackPanel>(emptyWindow, "EmptyState").Visibility == Visibility.Visible, "Fresh vault has a real empty state, no fake notes");
    emptyWindow.ExitFromTray();
    {
        L10n.Use("ar");
        var rtl = new MainWindow(emptySession); rtl.Show(); Pump();
        Check(rtl.FlowDirection == FlowDirection.RightToLeft && Find<TextBlock>(rtl, "ListHeading").Text == L10n.T("MyNotes"), "Arabic window mirrors the layout and shows Arabic labels");
        rtl.ExitFromTray();
        L10n.Use("ja");
        var ja = new MainWindow(emptySession); ja.Show(); Pump();
        Check(ja.FlowDirection == FlowDirection.LeftToRight && Find<TextBlock>(ja, "ListHeading").Text == "マイノート", "Japanese window shows Japanese labels");
        ja.ChangeLanguage("de");
        Check(ja.RestartRequested && !ja.IsVisible && L10n.Detect(Path.GetDirectoryName(emptySession.FilePath)!) == "de", "Choosing a language saves it and asks for a restart");
        L10n.Use("en");
    }
    }
}
