import {id,enc,random,b64,un64,derive,mac,verifyMac,seal,open,encryptFile,decryptFile} from './crypto.js';
const $=x=>document.getElementById(x);
let db,keys,device,notes=[],purges=[],current=null,trash=false,socket=null,ready=false,receiving=null,serverNonce,clientNonce,queue=Promise.resolve(),urls=[],retry;
const MAX_FILE=256*1024*1024;
function notice(s){$('notice').textContent=s;}
function run(fn){queue=queue.then(fn).catch(e=>{console.error(e);notice('İşlem tamamlanamadı: '+e.message);});return queue;}
function request(store,mode,fn){return new Promise((resolve,reject)=>{const tx=db.transaction(store,mode),r=fn(tx.objectStore(store));tx.oncomplete=()=>resolve(r?.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Depolama başarısız'));});}
const get=(s,k)=>request(s,'readonly',t=>t.get(k)), put=(s,k,v)=>request(s,'readwrite',t=>t.put(v,k)), del=(s,k)=>request(s,'readwrite',t=>t.delete(k));
async function persist(n){await put('notes',n.Id,{id:n.Id,rev:n.Revision,blob:await seal(keys,n)});}
async function savePurges(){await put('meta','purges',purges);}
function same(a,b){return a.Title===b.Title&&a.Text===b.Text&&a.Pinned===b.Pinned&&a.Deleted===b.Deleted&&JSON.stringify(a.Attachments)===JSON.stringify(b.Attachments);}
function send(m){if(ready&&socket?.readyState===1)socket.send(JSON.stringify(m));}
async function sendNote(n){send({t:'note',id:n.Id,rev:n.Revision,blob:b64(await seal(keys,n)),base:await get('base',n.Id)});}
async function localSave(n){await persist(n);await put('pending',n.Id,true);await sendNote(n);send({t:'flush'});renderList();}
function touch(n){n.Revision++;n.Updated=new Date().toISOString();}
function renderList(){const list=$('list');list.replaceChildren();const q=$('search').value.toLocaleLowerCase();for(const n of notes.filter(n=>n.Deleted===trash&&(n.Title+' '+n.Text+' '+n.Attachments.map(a=>a.Name).join(' ')).toLocaleLowerCase().includes(q)).sort((a,b)=>Number(b.Pinned)-Number(a.Pinned)||Date.parse(b.Updated)-Date.parse(a.Updated))){const b=document.createElement('button'),title=document.createElement('strong'),small=document.createElement('small');title.textContent=(n.Pinned?'● ':'')+(n.Title||'Yeni not');small.textContent=n.Text||`${n.Attachments.length} ek`;b.append(title,small);if(n.Id===current?.Id)b.className='selected';b.onclick=()=>run(()=>show(n));list.append(b);}}
async function show(n){current=n;$('editor').hidden=!n;document.body.classList.toggle('editing',!!n);for(const url of urls)URL.revokeObjectURL(url);urls=[];$('attachments').replaceChildren();if(!n){renderList();return;}$('title').value=n.Title;$('body').value=n.Text;$('title').disabled=$('body').disabled=n.Deleted;$('delete').hidden=$('attachLabel').hidden=$('pin').hidden=n.Deleted;$('restore').hidden=$('purge').hidden=!n.Deleted;$('pin').textContent=n.Pinned?'Sabitlemeyi kaldır':'Sabitle';renderList();for(const a of n.Attachments){const box=document.createElement('div'),link=document.createElement('a');link.textContent=a.Name;box.append(link);$('attachments').append(box);const encrypted=await get('files',a.Id);if(!encrypted){link.textContent+=' · aktarım bekleniyor';continue;}const url=URL.createObjectURL(await decryptFile(encrypted,a));urls.push(url);link.href=url;link.download=a.Name;if(a.MediaType.startsWith('image/')||a.MediaType.startsWith('video/')){const media=document.createElement(a.MediaType.startsWith('image/')?'img':'video');media.src=url;if(media.tagName==='VIDEO'){media.controls=true;media.preload='metadata';}box.prepend(media);}if(!n.Deleted){const remove=document.createElement('button');remove.textContent='Eki kaldır';remove.onclick=()=>run(async()=>{if(!confirm('Bu ek nottan kaldırılsın mı?'))return;n.Attachments=n.Attachments.filter(x=>x.Id!==a.Id);touch(n);await localSave(n);await show(n);});box.append(remove);}}}
async function manifest(){const files=await request('files','readonly',s=>s.getAllKeys());return {t:'manifest',notes:notes.map(n=>({id:n.Id,rev:n.Revision,updated:Date.parse(n.Updated)})),purged:purges,files};}
async function wantFiles(){const missing=[];for(const a of notes.flatMap(n=>n.Attachments))if(!await get('files',a.Id))missing.push(a.Id);if(missing.length)send({t:'want-files',ids:[...new Set(missing)]});}
async function receiveNote(m){const n=await open(keys,m.id,m.rev,un64(m.blob));if(purges.some(p=>p.id===n.Id&&p.rev>=n.Revision))return;const old=notes.find(x=>x.Id===n.Id);if(m.replyRev!=null){await put('base',n.Id,{rev:m.rev,blob:m.blob});if(old&&old.Revision>m.replyRev&&await get('pending',old.Id))return;}else {if(old&&old.Revision>n.Revision)return;if(old&&await get('pending',old.Id)&&!same(old,n))return;}if(old)notes[notes.indexOf(old)]=n;else notes.push(n);await persist(n);await put('base',n.Id,{rev:m.rev,blob:m.blob});await del('pending',n.Id);if(current?.Id===n.Id)await show(n);else renderList();}
async function transfer(ids){for(const aid of ids){const b=await get('files',aid);if(!b)continue;send({t:'file',id:aid,size:b.size});for(let at=0;at<b.size;at+=262144){while(socket?.readyState===1&&socket.bufferedAmount>1048576)await new Promise(r=>setTimeout(r,30));if(!ready||socket?.readyState!==1)return;socket.send(await b.slice(at,at+262144).arrayBuffer());}send({t:'file-end',id:aid});}}
async function handle(data){if(typeof data!=='string'){if(!receiving)throw Error('Beklenmeyen dosya');receiving.parts.push(data);receiving.have+=data.byteLength;if(receiving.have>receiving.size)throw Error('Dosya boyutu aşıldı');return;}const m=JSON.parse(data);switch(m.t){
case 'challenge':serverNonce=un64(m.nonce);clientNonce=random(32);socket.send(JSON.stringify({t:'auth',nonce:b64(clientNonce),mac:b64(new Uint8Array(await mac(keys,'client',serverNonce,clientNonce)))}));break;
case 'welcome':if(!await verifyMac(keys,un64(m.mac),'server',clientNonce,serverNonce)){socket.close();throw Error('Bilgisayar doğrulanamadı');}ready=true;$('status').textContent='Bağlı · eşitleniyor';send(await manifest());break;
case 'manifest':{for(const n of notes){const peer=m.notes.find(x=>x.id===n.Id);if(!m.purged.some(p=>p.id===n.Id&&p.rev>=n.Revision)&&(!peer||n.Revision>peer.rev||(n.Revision===peer.rev&&(Date.parse(n.Updated)!==peer.updated||await get('pending',n.Id)))))await sendNote(n);}for(const p of purges)send({t:'purge',...p});send({t:'done'});break;}
case 'note':await receiveNote(m);break;
case 'purge':{const n=notes.find(x=>x.Id===m.id);if(n&&n.Revision<=m.rev){notes=notes.filter(x=>x!==n);await del('notes',n.Id);await del('pending',n.Id);if(current?.Id===n.Id)await show(null);}if(!purges.some(p=>p.id===m.id&&p.rev>=m.rev)){purges=purges.filter(p=>p.id!==m.id);purges.push({id:m.id,rev:m.rev});await savePurges();}renderList();break;}
case 'flush':case 'done':await wantFiles();$('status').textContent='Bağlı · notlar eşitlendi';break;
case 'want-files':await transfer(m.ids);break;
case 'file':if(m.size<24||m.size>MAX_FILE+65536||!/^[a-f0-9]{32}$/.test(m.id))throw Error('Geçersiz dosya');receiving={id:m.id,size:m.size,have:0,parts:[]};break;
case 'file-end':{const r=receiving;receiving=null;if(!r||r.id!==m.id||r.have!==r.size)throw Error('Eksik dosya');const a=notes.flatMap(n=>n.Attachments).find(a=>a.Id===r.id);if(!a)break;const blob=new Blob(r.parts);await decryptFile(blob,a);await put('files',a.Id,blob);if(current?.Attachments.some(x=>x.Id===a.Id))await show(current);break;}
case 'rejected':socket.close();throw Error('Eşleştirme kabul edilmedi. Bilgisayardaki QR kodla yeniden eşleştir.');
}}
function connect(){clearTimeout(retry);if(!keys||socket&&socket.readyState<2)return;ready=false;$('status').textContent='Bağlanıyor…';const ws=new WebSocket('wss://'+location.host+'/sync');socket=ws;ws.binaryType='arraybuffer';ws.onopen=()=>ws.send(JSON.stringify({t:'hello',protocol:1,device,name:'iPhone'}));ws.onmessage=e=>run(async()=>{if(socket!==ws)return;try{await handle(e.data);}catch(error){ws.close();throw error;}});ws.onclose=()=>{if(socket!==ws)return;ready=false;receiving=null;$('status').textContent='Çevrimdışı · notlar cihazda';retry=setTimeout(connect,10000);};ws.onerror=()=>{};}
async function applyKey(raw){if(raw.length!==32)throw Error('Eşleştirme bilgisi geçersiz');if(keys&&!confirm('Eşleştirmeyi yenilemek mevcut notları yeni anahtarla şifreler. Devam edilsin mi?'))return;keys=await derive(raw);raw.fill(0);await put('meta','keys',keys);for(const n of notes)await persist(n);history.replaceState(null,'','/');$('pairLink').value='';$('pairCode').value='';$('pair').hidden=true;$('workspace').hidden=false;socket?.close();socket=null;connect();if(!navigator.standalone)notice('Eşleşti. Şimdi Paylaş → Ana Ekrana Ekle; ana ekrandan açınca bilgisayardaki kodu bir kez daha gir.');}
async function pair(link){const u=new URL(link,location.href);if(u.origin!==location.origin)throw Error('Bu bağlantı farklı bir bilgisayara ait. Bağlantıyı Safari’de aç.');await applyKey(un64(new URLSearchParams(u.hash.slice(1)).get('k')||''));}
// The short code shown on the PC fetches the sync key over TLS; five wrong tries or ten minutes burn the code.
async function pairWithCode(code){code=code.replace(/\D/g,'');if(code.length!==6)throw Error('Bilgisayarda görünen 6 haneli kodu yaz.');const r=await fetch('/pair',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code})});if(!r.ok)throw Error('Kod kabul edilmedi. Bilgisayardaki eşitleme penceresi açık mı? Yeni kod alıp tekrar dene.');const {k}=await r.json();await applyKey(un64(k));}
$('pairButton').onclick=()=>run(()=>pairWithCode($('pairCode').value));$('pairCode').onkeydown=e=>{if(e.key==='Enter')$('pairButton').click();};$('pairLinkButton').onclick=()=>run(()=>pair($('pairLink').value));$('sync').onclick=()=>run(async()=>{if(ready)send(await manifest());else connect();});$('search').oninput=renderList;
$('new').onclick=()=>run(async()=>{const now=new Date().toISOString(),n={Id:id(),Title:'',Text:'',Created:now,Updated:now,Pinned:false,Deleted:false,DeletedAt:null,Revision:1,Attachments:[]};notes.push(n);trash=false;await localSave(n);await show(n);$('title').focus();});
for(const [key,prop] of [['title','Title'],['body','Text']])$(key).oninput=()=>{const n=current,value=$(key).value;run(async()=>{if(!n||n.Deleted)return;n[prop]=value;touch(n);await localSave(n);});};
$('all').onclick=()=>run(async()=>{trash=false;await show(null);});$('trash').onclick=()=>run(async()=>{trash=true;await show(null);});$('back').onclick=()=>run(()=>show(null));
for(const action of ['pin','delete','restore'])$(action).onclick=()=>run(async()=>{const n=current;if(!n)return;if(action==='pin')n.Pinned=!n.Pinned;else {n.Deleted=action==='delete';n.DeletedAt=n.Deleted?new Date().toISOString():null;}touch(n);await localSave(n);await show(action==='pin'?n:null);});
$('purge').onclick=()=>run(async()=>{const n=current;if(!n||!confirm('Bu not kalıcı olarak silinsin mi?'))return;purges.push({id:n.Id,rev:n.Revision});await savePurges();await del('notes',n.Id);notes=notes.filter(x=>x!==n);send({t:'purge',id:n.Id,rev:n.Revision});send({t:'flush'});await show(null);});
$('files').onchange=()=>{const files=[...$('files').files],n=current;$('files').value='';run(async()=>{if(!n||n.Deleted)return;for(const file of files){if(file.size>MAX_FILE)throw Error('Telefonda ek başına sınır 256 MB.');if(!/^(image|video)\//.test(file.type)&&!/\.(heic|heif|mov|mp4|m4v|jpe?g|png|gif|webp)$/i.test(file.name))throw Error('Fotoğraf veya video seç.');notice('Ek şifreleniyor… ('+(file.size/1048576).toFixed(1)+' MB, olduğu gibi)');const encrypted=await encryptFile(file);await put('files',encrypted.meta.Id,encrypted.blob);n.Attachments.push(encrypted.meta);touch(n);await localSave(n);}if(ready)send(await manifest());await show(n);notice('Ekler şifreli kaydedildi.');});};
document.addEventListener('visibilitychange',()=>{if(!document.hidden)run(async()=>{if(ready)send(await manifest());else connect();});});window.addEventListener('online',connect);
run(async()=>{db=await new Promise((resolve,reject)=>{const r=indexedDB.open('notebook',2);r.onupgradeneeded=()=>{for(const name of ['meta','notes','files','pending','base'])if(!r.result.objectStoreNames.contains(name))r.result.createObjectStore(name);};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});keys=await get('meta','keys');device=await get('meta','device');if(!device){device=id();await put('meta','device',device);}purges=await get('meta','purges')||[];if(keys){for(const row of await request('notes','readonly',s=>s.getAll()))notes.push(await open(keys,row.id,row.rev,row.blob));}
if(location.hash.includes('k='))await pair(location.href);$('pair').hidden=!!keys;$('workspace').hidden=!keys;renderList();if(keys){connect();navigator.storage?.persist?.().catch(()=>{});}if('serviceWorker'in navigator)await navigator.serviceWorker.register('/sw.js');if(!navigator.standalone)notice('Safari → Paylaş → Ana Ekrana Ekle; sonra Notlar’ı ana ekrandan aç.');});
