export const enc=new TextEncoder(), dec=new TextDecoder();
export const random=n=>crypto.getRandomValues(new Uint8Array(n));
export const cat=(...xs)=>{const b=new Uint8Array(xs.reduce((s,x)=>s+x.length,0));let p=0;for(const x of xs){b.set(x,p);p+=x.length;}return b;};
export function b64(b){let s='';for(let i=0;i<b.length;i+=8192)s+=String.fromCharCode(...b.subarray(i,i+8192));return btoa(s);}
export const un64=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
export const id=()=>crypto.randomUUID().replaceAll('-','');
export async function derive(raw){const k=await crypto.subtle.importKey('raw',raw,'HKDF',false,['deriveKey']);const base={name:'HKDF',hash:'SHA-256',salt:new Uint8Array()};return {auth:await crypto.subtle.deriveKey({...base,info:enc.encode('notlar-sync-auth')},k,{name:'HMAC',hash:'SHA-256',length:256},false,['sign','verify']),content:await crypto.subtle.deriveKey({...base,info:enc.encode('notlar-sync-content')},k,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])};}
export const mac=(keys,role,a,b)=>crypto.subtle.sign('HMAC',keys.auth,cat(enc.encode(role),a,b));
export const verifyMac=(keys,value,role,a,b)=>crypto.subtle.verify('HMAC',keys.auth,value,cat(enc.encode(role),a,b));
const aad=(id,rev)=>enc.encode('Notlar/note/'+id+'/'+rev);
export async function seal(keys,n){const iv=random(12);return cat(iv,new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:aad(n.Id,n.Revision)},keys.content,enc.encode(JSON.stringify(n)))));}
export async function open(keys,id,rev,b){const p=await crypto.subtle.decrypt({name:'AES-GCM',iv:b.slice(0,12),additionalData:aad(id,rev)},keys.content,b.slice(12));const n=JSON.parse(dec.decode(p));if(n.Id!==id||n.Revision!==rev||!Array.isArray(n.Attachments))throw Error('Not doğrulanamadı');return n;}
function chunkParams(header,id,i,last){const index=new Uint8Array(4);new DataView(index.buffer).setUint32(0,i);return {name:'AES-GCM',iv:cat(header.slice(16,24),index),additionalData:cat(header,enc.encode(id),index,new Uint8Array([last?1:0]))};}
export async function encryptFile(file){const aid=id(),raw=random(32),key=await crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt']);const header=new Uint8Array(24);header.set(enc.encode('NLA1'));const v=new DataView(header.buffer);v.setInt32(4,1048576,true);v.setBigInt64(8,BigInt(file.size),true);header.set(random(8),16);const chunks=[header];let i=0;do{const start=i*1048576,end=Math.min(file.size,start+1048576);const p=await file.slice(start,end).arrayBuffer();chunks.push(await crypto.subtle.encrypt(chunkParams(header,aid,i,end===file.size),key,p));i++;}while(i*1048576<file.size);return {meta:{Id:aid,Name:/^tempImage/i.test(file.name)?'IMG '+new Date().toISOString().slice(0,19).replace('T',' ').replaceAll(':','.')+(file.name.match(/\.[a-z0-9]+$/i)?.[0]||'.heic'):file.name,MediaType:file.type||(/\.hei[cf]$/i.test(file.name)?'image/heic':/\.(mov)$/i.test(file.name)?'video/quicktime':/\.(mp4|m4v)$/i.test(file.name)?'video/mp4':'application/octet-stream'),Size:file.size,Key:b64(raw),Sha256:'',Width:0,Height:0,Added:new Date().toISOString()},blob:new Blob(chunks)};}
// keep=false only checks every piece (a whole large video never sits in memory) and returns nothing.
export async function decryptFile(blob,a,keep=true){const h=new Uint8Array(await blob.slice(0,24).arrayBuffer());if(h.length!==24||dec.decode(h.slice(0,4))!=='NLA1')throw Error('Ek dosyası bozuk');const v=new DataView(h.buffer),size=Number(v.getBigInt64(8,true)),chunk=v.getInt32(4,true);if(size!==a.Size||chunk<=0||chunk>67108864||blob.size!==24+size+Math.max(1,Math.ceil(size/chunk))*16)throw Error('Ek boyutu geçersiz');const k=await crypto.subtle.importKey('raw',un64(a.Key),'AES-GCM',false,['decrypt']);const parts=[];let at=24,remaining=size,i=0;do{const n=Math.min(chunk,remaining);remaining-=n;const p=await crypto.subtle.decrypt(chunkParams(h,a.Id,i++,remaining===0),k,await blob.slice(at,at+n+16).arrayBuffer());if(keep)parts.push(p);at+=n+16;}while(remaining>0);return keep?new Blob(parts,{type:a.MediaType}):null;}
